version: '3.7'
services: 
  gqlpdsslogtrace-mysql:
    container_name: gqlpdsslogtrace-mysql8
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${GQLPDSSLOGTRACE_DBPASSWORD:-dbpassword}
    ports:
      - "${GQLPDSSLOGTRACE_MYSQL_PORT:-3308}:3306"
    platform: linux/x86_64
    volumes:
      - ~/opt/dockerMysql8.0.28:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 60
  gqlpdsslogtrace-php:
    depends_on:
      gqlpdsslogtrace-mysql:
        condition: service_healthy
    container_name: gqlpdsslogtrace-php7.4
    image: jesusabarcag/php-dev:php7.4
    volumes: 
      - ..:/var/www/html
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./commands:/home/commands
    ports: 
      - "${GQLPDSSLOGTRACE_APP_PORT:-8080}:8080"
    entrypoint: sh -c "/home/commands/run.sh"
    restart: "no"
    platform: linux/x86_64
    environment:
      - GQLPDSSLOGTRACE_APP_PORT=${GQLPDSSLOGTRACE_APP_PORT:-8080}
      - GQLPDSSLOGTRACE_DBUSER=${GQLPDSSLOGTRACE_DBUSER:-root}
      - GQLPDSSLOGTRACE_DBPASSWORD=${GQLPDSSLOGTRACE_DBPASSWORD:-dbpassword}
      - GQLPDSSLOGTRACE_DBNAME=${GQLPDSSLOGTRACE_DBNAME:-gqlpdss_logtracedb}
      - GQLPDSSLOGTRACE_DBHOST=gqlpdsslogtrace-mysql